cmd: add new `describe-image` command
osbuild/image-builder-cli pull request #9
Opened 2024-12-12 10:24 UTC by mvo5

[draft as it is build on top of #6]

This commit adds a new `describe-image` comamnd that contains
the details about the given image type. The output is yaml as
it is both nicely human readable and also machine readable.

The output looks like this:
```yaml
$ ./image-builder describe-image rhel-9.1 tar
distro: rhel-9.1
type: tar
arch: x86_64
os_vesion: "9.1"
bootmode: none
partition_type: ""
default_filename: root.tar.xz
packages:
  include:
    - policycoreutils
    - selinux-policy-targeted
    - selinux-policy-targeted
  exclude:
    - rng-tools
```

Thanks to Ondrej Budai for the idea and the example.

2025-01-19 21:58 UTC, supakeen commented
Since #6 has landed for a while now we can probably undraft this.

One thing, perhaps we can call it `describe`? All commands work with images.

2025-01-28 13:57 UTC, mvo5 commented
While looking at https://github.com/osbuild/bootc-image-builder/pull/808 I was wondering if we could make it easier to figure out what packages are part of an image and then I did remember this PR. I think the output needs work and it ideally would be an input to https://github.com/osbuild/images/pull/1104 but we are not there yet.

So I was thinking in the meantime we simply could have a warning and mark it as an unstable feature (and deliberately break the yaml from being parseable) and then it would be a useful debug tool already. Wdyt?

2025-01-29 11:47 UTC, achilleas-k requested changes

2025-01-29 11:47 UTC, achilleas-k commented on cmd/image-builder/main.go
> +		Args:         cobra.ExactArgs(1),
This should be 2.

2025-01-29 11:48 UTC, achilleas-k requested changes

2025-01-29 11:48 UTC, achilleas-k commented on cmd/image-builder/main.go
> +		Use:          "describe-image <distro> <image-type>",
```suggestion
		Use:          "describe-image <image-type>",
```
Distro is an optional arg, right?

2025-01-29 11:48 UTC, achilleas-k commented on cmd/image-builder/main.go
> +		Args:         cobra.ExactArgs(1),
My mistake.  It's just the use line and example that are wrong.

2025-01-29 12:08 UTC, thozza commented on cmd/image-builder/describeimg.go
> +	Packages *packagesYAML `yaml:"packages"`
I think the pipeline should be added here, since otherwise the output won't be complete for installer images. It may make sense to do it in a smart way - include pipeline only if here are multiple pipelines with a package set defined? :thinking:

2025-01-29 12:08 UTC, thozza commented on cmd/image-builder/describeimg.go
> +	// and inlcude what pipeline needs the package set too?
Personally, I think that merging pipeline package sets makes little sense because it will be confusing and impossible to determine what will be in the "payload" and what will be installed, e.g., in the Anaconda ISO for installer images.

2025-01-29 15:41 UTC, mvo5 commented on cmd/image-builder/main.go
> +		Use:          "describe-image <distro> <image-type>",
Thanks, fixed now.

2025-01-29 15:42 UTC, mvo5 commented on cmd/image-builder/describeimg.go
> +	Packages *packagesYAML `yaml:"packages"`
Makes sense, I updated the commit to include the pipelines, I hope this captures what you wrote.

2025-01-31 07:26 UTC, thozza commented
@mvo5 I randomly picked one failed RPM build in COPR, and it seems to be failing on unit tests, which is strange because they passed in the GH Action. Could you please take a look?

2025-01-31 07:32 UTC, thozza requested changes
LGTM, but unit tests are failing in RPM builds in COPR, so blocking the PR, because those are probably not required.

2025-01-31 07:32 UTC, thozza commented on cmd/image-builder/main.go
> +	// XXX: add --format=json too?
I had the same thought and it would mean basically stripping the `YAML` from struct names such as `describeImgYAML` and adding tags for `json. I think that it would make sense and should be fairly easy to do. One can then use `jq` to extract whatever information they need and things become interesting :sweat_smile:

2025-01-31 08:17 UTC, mvo5 commented on cmd/image-builder/main.go
> +	// XXX: add --format=json too?
Thanks, yeah, that makes sense.

I updated the PR, the test was failing because I forgot to pass --arch in the describe-image smoke test so on non-x86 it would fail. this is fixed now.

2025-01-31 08:37 UTC, thozza approved these changes

2025-01-31 08:43 UTC, supakeen approved these changes

2025-01-31 08:44 UTC, supakeen commented
@thozza you have requested changes still :)

2025-01-31 09:48 UTC, mvo5 commented
@supakeen its actually @achilleas-k how still has a "change-request" open (the GH ui is a bit confusing)

2025-01-31 09:53 UTC, supakeen commented
Sorry!

2025-01-31 10:57 UTC, achilleas-k approved these changes

2025-01-31 10:58 UTC, merged